
export const GET_SHOWS_HOME_PEDDING = 'REQUEST_SHOWS_HOME_PENDING';
export const GET_SHOWS_HOME_SUCCESS = 'REQUEST_SHOWS_HOME_SUCCESS';
export const GET_SHOWS_HOME_FAILED = 'REQUEST_SHOWS_HOME_FAILED';

export const GET_SHOWS_MOVIES_PEDDING = 'REQUEST_SHOWS_MOVIES_PENDING';
export const GET_SHOWS_MOVIES_SUCCESS = 'REQUEST_SHOWS_MOVIES_SUCCESS';
export const GET_SHOWS_MOVIES_FAILED = 'REQUEST_SHOWS_MOVIES_FAILED';

export const GET_SHOWS_TV_PEDDING = 'REQUEST_SHOWS_TV_PENDING';
export const GET_SHOWS_TV_SUCCESS = 'REQUEST_SHOWS_TV_SUCCESS';
export const GET_SHOWS_TV_FAILED = 'REQUEST_SHOWS_TV_FAILED';
